/*
 * Spring Boot使用 Swagger2 构建RestFul API
 * 接口文档
 *
 * OpenAPI spec version: v1
 * Contact: 123456@dongfangdi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.testclient;


import com.bidewu.api.ImportHouseApi;
import com.bidewu.invoker.ApiException;
import com.bidewu.model.*;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import java.math.BigDecimal;
import java.util.Arrays;


/**
 * ImportHouseApi测试类
 */

@Controller
@RequestMapping(path = "/house")
public class ImportHouseApiTest {

    private final ImportHouseApi api = new ImportHouseApi();
    public static final String AUTHORIZATION = "a139963e290b0d1954acd3cc30ef49177628b4b7";

    /**
     * 出租房源下架
     *
     * 出租房源下架
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @RequestMapping(path = "/dropHouseRent")
    @ResponseBody
    public HouseRentResponse dropHouseRentTest(boolean isDebug) throws ApiException {
        ApiDropHouseRentDO dropHouseRentDO = new ApiDropHouseRentDO();
        dropHouseRentDO.setCompany("5i5j");
        dropHouseRentDO.setSourceHouseId("5e8dfaf9-3fc9-c2ee-3338-08d5a10be75e");
        String authorization = AUTHORIZATION;
        HouseRentResponse response = api.dropHouseRent(dropHouseRentDO, authorization, isDebug);
        return response;
    }

    /**
     * 出售房源下架
     *
     * 出售房源下架
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @RequestMapping(path = "/dropHouseSell")
    @ResponseBody
    public Object dropHouseSellTest(boolean isDebug) throws ApiException {
        HouseDropDO houseDropDO = new HouseDropDO();
        houseDropDO.setCity("sh");
        houseDropDO.setCityId(13);
        houseDropDO.setFangyuanId("5e8dfaf9-3fc9-c2ee-3338-08d5a10be75e");
        houseDropDO.setOfCompanyEn("5i5j");
        String authorization = AUTHORIZATION;
        Object response = api.dropHouseSell(houseDropDO, authorization, isDebug);
        return response;
    }

    /**
     * 导入或更新出租房源
     *
     * 导入或更新出租房源
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @RequestMapping(path = "/importHouseRent")
    @ResponseBody
    public HouseRentResponse importHouseRentTest(boolean isDebug) throws ApiException {
        ApiHouseRentDO apiHouseRentDO = buildApiHouseRentDO();
        String authorization = AUTHORIZATION;
        HouseRentResponse response = api.importHouseRent(apiHouseRentDO, authorization, isDebug);
        return response;
    }

    public ApiHouseRentDO buildApiHouseRentDO(){
        ApiHouseRentDO apiHouseRentDO = new ApiHouseRentDO();
        apiHouseRentDO.setSourceHouseId("5e8dfaf9-3fc9-c2ee-3338-08d5a10be75e");
        apiHouseRentDO.setLoupanName("远洋山水");
        apiHouseRentDO.setFloor(1);
        apiHouseRentDO.setRoom(2);
        apiHouseRentDO.setHall(1);
        apiHouseRentDO.setArea(BigDecimal.valueOf(120));
        apiHouseRentDO.setRentPrice(BigDecimal.valueOf(1200));
        apiHouseRentDO.setPayMode(1);
        apiHouseRentDO.setHouseTitle("大羊坊");
        apiHouseRentDO.setRentType(1);
        apiHouseRentDO.setCategory(1);
        apiHouseRentDO.setLogoPic("https://img0gz.centainfo.com/images/20180223/100150_6b05b3d1-4114-4142-8552-c320c1f60345.jpg");
        apiHouseRentDO.setAgentName("罗远思");
        apiHouseRentDO.setAgentTel("15735291367");
        apiHouseRentDO.setCompany("5i5j");
        return apiHouseRentDO;
    }

    /**
     * 导入或更新出售房源
     *
     * 导入或更新出售房源
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @RequestMapping(path = "/importHouseSell")
    @ResponseBody
    public TouTiaoResult importHouseSellTest(boolean isDebug, String houseId) throws ApiException {
        HouseImportDO houseImportDO = buildDo(houseId);
        String authorization = AUTHORIZATION;
        TouTiaoResult response = api.importHouseSell(houseImportDO, authorization, isDebug);
        return response;
    }

    public HouseImportDO buildDo(String houseId){
        HouseImportDO houseImportDO = new HouseImportDO();

        houseImportDO.setLoupanId("259820");
        houseImportDO.setProjName("苹果园四区");
        houseImportDO.setCity("sh");
        houseImportDO.setAddress("天河区华景东路888号");
        houseImportDO.setAgentInfoCard("https://pic.centanet.com/guangzhou/pic/agent/6624_jw.jpg");
        houseImportDO.setAgentName("罗远思");
        houseImportDO.setAgentTel("13922203003");
        houseImportDO.setDisplayTel("18888888888");
        houseImportDO.setBuildArea(113.0);
        houseImportDO.setFangyuanId(houseId);
        houseImportDO.setFitment(3);
        houseImportDO.setFloor("中层");
        houseImportDO.setForward(6);
        houseImportDO.setHall(2);
        houseImportDO.setIsReal(0);
        houseImportDO.setHouseDesc("1；新装修，宽敞的40平方大厅，舒适大气\\n\\n2；证满五年一手业主，不占用华景小113中\\n\\n3；送80平方大平台，养鱼种花是不错的选择\\n\\n公交配套：华景公交总站，出行有B9，130、194、239、293、191等线路，离上社BRt步行7分钟\\n生活配套：9大银行，万佳，胜佳超市，喜市多，钱大妈，星巴克，连锁美容院等\\n教育配套：华景共有5所幼稚园，琴、棋、书、画等培训课程很丰富\\n\\n本人任职中原11年，一直专注华景房源，熟悉每个组团，了解贷款政策及交易税费，欢迎来电小罗13922203003");
        houseImportDO.setHouseTitle("无敌大平台 宽敞4房 厅大房大 钥匙房源欢迎对比");
        houseImportDO.setHouseType(1);

        String[] layoutPics =
                {"https://img0gz.centainfo.com/images/20180223/100150_6b05b3d1-4114-4142-8552-c320c1f60345.jpg",
                        "https://img0gz.centainfo.com/images/20180223/100148_712b3967-8f27-413c-847d-53fcd2d3cc1c.jpg"};

        houseImportDO.setLayoutPic(Arrays.asList(layoutPics));

        houseImportDO.setLogoPic("https://img0gz.centainfo.com/images/20180223/100150_6b05b3d1-4114-4142-8552-c320c1f60345.jpg");

        houseImportDO.setPrice(630.0);
        houseImportDO.setRoom(3);

        String[] roomPics = {"https://img0gz.centainfo.com/images/20180205/120046_1d7fc08c-4006-4db1-8c5c-3f0a63677b1a.jpg"};
        houseImportDO.setRoomPic(Arrays.asList(roomPics));

        Integer[] tags = {};
        houseImportDO.setTags(Arrays.asList(tags));
        houseImportDO.setToilet(1);
        houseImportDO.setTotalFloor(29);
        houseImportDO.setYear("2003");
        houseImportDO.setOfCompanyEn("5i5j");
        return houseImportDO;
    }
    
}
